import type { ExtensionData, FormatFileResult } from '../../../types/emitter.types.ts';

export function formatExtensionFile(
  data: ExtensionData,
): FormatFileResult {

  const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  [
    ${data.variables.map(variable => `"${variable}"`).join(",\n")}
  ]
  `;

  const outputFile = "metadata/extension.jsonc"

  return { outputFile, content, kind: "extension" };
}