import type { FormatFileResult, PresetFileData } from '../../../types/emitter.types.ts';



export function formatPresetFiles(presetData: PresetFileData[]): FormatFileResult[] {
  const files: FormatFileResult[] = []

  for (const entry of presetData) {

    const sortedSelectors = entry.selectors.toSorted((a, b) => a.localeCompare(b));


    const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  
  import css from "${entry.cssImport}";
  
  export const ${entry.presetName} = {
  ${sortedSelectors
        .map(selector => `  ${selector}: css.${selector},`)
        .join("\n")}
  } as const;
  
  export type ${entry.typeName} = keyof typeof ${entry.presetName};
  `;

    files.push({ outputFile: entry.outputFile, content, kind: "presets" })
  }

  return files
}