import type { FormatFileResult, PackageData } from '../../../types/emitter.types.ts';


export function formatPackageFile(data: PackageData): FormatFileResult {


  const output = data.fileNames
    .map(file => `export * from "./${file}"`)
    .join('\n')

  const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by Cascade-compiler.
  
  ${output}
  `;

  return { outputFile: data.outputFile, content, kind: "package" }
}
