import type { FormatFileResult, TokenGroupData } from '../../../types/emitter.types.ts';


export function formatTokenFiles(tokenGroupData: TokenGroupData[]): FormatFileResult[] {
  const files: FormatFileResult[] = []

  for (const entry of tokenGroupData) {

    const vars: string[] = [];

    for (const token of entry.tokens) {

      const varsRaw = token.variables.map((v) => {
        return `         ${v.key}: { name: "${v.cssName}", allowed: [${v.allowed.map((a) => `"${a}"`).join(",")}]}`
      }).join(",\n")

      const baseVar = `\n   ${token.infix}: {\n ${varsRaw} \n}`

      vars.push(baseVar)
    }

    const importStatement = `import type {
  StyleFromComponent,
  TokenComponent
} from "../../types/compiler.types.ts"`

    const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

${importStatement}

export const ${entry.styleName} = {
  component: "${entry.name}",

  vars: {   ${vars}
  }
} as const satisfies TokenComponent;

export type ${entry.typeName} = StyleFromComponent<typeof ${entry.styleName}>;
`;

    files.push({ outputFile: entry.outputFile, content, kind: "tokens" })
  }

  return files
}