import fs from "node:fs";
import path from "node:path";
import { toCamelCase } from '../../../shared/tokenUtils/stringFormaters.ts';
import { toPascalCase } from '../../../shared/tokenUtils/stringFormaters.ts';
import type { LoadedToken } from '@styleTokens/compiler/loaders/getToken.ts';

export default function generateTokenModule(token: LoadedToken): void {
  const pascalName = toPascalCase(token.name)
  const camelName = toCamelCase(token.name)

  const component = `${camelName}Style`;
  const typeName = `${pascalName}Style`;

  const generatedDir = path.resolve("./src/shared/generated/tokenModules");
  const tokenFile = path.join(generatedDir, `${camelName}.token.ts`);

  // const sortedVars = vars.toSorted((a, b) => a.localeCompare(b));

  const vars = token.vars
    .map((v) => {
      const name = v.name
        ? `name: "${v.name}",`
        : "";
      return `
    ${v.key}: {
      ${name}
      allowed: [${v.effectiveAllowed.map((a) => `"${a}"`).join(",")}],
    }`;
    })
    .join(",\n");

  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

export const ${component} = {
  component: "${token.name}",
  infix: "${token.infix}",

  vars: {
  ${vars}
  }
} as const satisfies TokenComponent;

export type ${typeName} = StyleFromVars<typeof ${component}.vars>;
`;

  fs.writeFileSync(tokenFile, content);
}