import fs from "node:fs";
import path from "node:path";
import { toCamelCase } from '../../../shared/tokenUtils/stringFormaters.ts';
import { toPascalCase } from '../../../shared/tokenUtils/stringFormaters.ts';

type PresetFileData = {
  name: string;
  file: string;
  selectors: string[];
};

export default function generatePresetFile({ name, file, selectors }: PresetFileData): void {
  const pascalName = toPascalCase(name)
  const camelName = toCamelCase(name)

  const component = `${camelName}Preset`;
  const typeName = `${pascalName}Preset`;

  const generatedDir = path.resolve("./src/shared/generated/presets");
  const presetFile = path.join(generatedDir, `${camelName}.preset.ts`);

  const sortedSelectors = selectors.toSorted((a, b) => a.localeCompare(b));

  let cssImport = path.relative(
    generatedDir,
    file
  );

  // make it valid for imports
  cssImport = cssImport.replaceAll("\\", "/");

  if (!cssImport.startsWith(".")) {
    cssImport = `${cssImport}`;
  }

  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

import css from "./${cssImport}";

export const ${component} = {
${sortedSelectors
      .map(selector => `  ${selector}: css.${selector},`)
      .join("\n")}
} as const;

export type ${typeName} = keyof typeof ${component};
`;

  fs.writeFileSync(presetFile, content);
}