import fs from "node:fs";
import path from "node:path";
import {
  toCamelCase,
  toPascalCase
} from "../../../shared/tokenUtils/stringFormaters.ts";
import resolveTokenImportPath from '../resolvers/resolveTokenImportPath.ts';

type Token = {
  name: string;
  file: string;
};

type TokenEntry = {
  name: string;
  file: string;
  camelName: string;
  pascalName: string;
  importName: string;
};

function dedupeEntries(
  entries: TokenEntry[],
  outputDir: string): TokenEntry[] {
  const seen = new Set();

  return entries.filter(({ file }) => {
    if (!file) {
      throw new Error("❌ Missing file");
    }

    const importPath = resolveTokenImportPath(file, outputDir);

    if (seen.has(importPath)) {
      return false;
    }

    seen.add(importPath);

    return true;
  });
}


export default function generateTokenStyles(tokens: Token[]): void {

  const outputDir = path.resolve("./src/shared/generated/tokenStyles");

  const outputFile = path.join(outputDir, "tokenStyles.ts");


  const entries = tokens
    .toSorted((a, b) => a.name.localeCompare(b.name))
    .map(({ name, file }) => {
      const camelName = toCamelCase(name);

      return {
        name,
        file,
        camelName,
        pascalName: toPascalCase(name),
        importName: `${camelName}Json`,
      };
    });

  // One entry per token
  const tokenEntries = dedupeEntries(entries, outputDir);

  const imports = tokenEntries
    .map(({ file, importName }) => {
      const importPath = resolveTokenImportPath(
        file,
        outputDir
      );

      return `import ${importName} from "${importPath}";`;
    })
    .join("\n");

  const exports = tokenEntries
    .map(({ camelName, pascalName, importName }) =>
      `
export const ${camelName}Style = convertJson(${importName});

export type ${pascalName}Style =
  StyleFromVars<
    typeof ${camelName}Style.vars,
    typeof ${camelName}Style.alwaysAllowed
  >;
`
    )
    .join("\n");


  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

import type {
  StyleFromVars
} from "@shared/tokenUtils/compiler.types";

import {
  convertJson
} from "@shared/tokenUtils/toRuntimeToken.ts";

${imports}

${exports}
`;


  fs.mkdirSync(outputDir, { recursive: true, });

  fs.writeFileSync(outputFile, content);
}