import path from 'node:path';
import type { FormatResult } from '../generateOutput.ts';
import type { CssVarString } from '@shared/tokenUtils/compiler.types.ts';

export function formatExtensionFile(
  variables: CssVarString[],
): FormatResult {
  const filePath = path.resolve(
    "./src/shared/generated/metadata/cssVariables.generated.jsonc",
  );

  const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  [
    ${variables.map(variable => `"${variable}"`).join(",\n")}
  ]
  `;

  return { filePath, content };
}