import path from 'node:path';
import type { FormatResult } from '../generateOutput.ts';
import type { ExtensionData } from '../../extract/assemblers/assembleExtensionData.ts';

export function formatExtensionFile(
  data: ExtensionData,
): FormatResult {
  const filePath = path.resolve(
    "./src/shared/generated/metadata/cssVariables.generated.jsonc",
  );

  const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  [
    ${data.variables.map(variable => `"${variable}"`).join(",\n")}
  ]
  `;

  return { filePath, content };
}