import path from 'node:path';
import type { TokenGroupFileData } from '../../extract/assemblers/assembleTokenData.ts';
import type { FormatResult } from '../generateOutput.ts';
import { toCssVar } from '../../../../shared/tokenUtils/stringFormaters.ts';


export function formatLspFile(tokenGroupData: TokenGroupFileData[]): FormatResult {
  const output: string[] = []

  const filePath = path.resolve("./src/shared/generated/metadata/cssVariables.generated.ts")

  for (const entry of tokenGroupData) {
    for (const token of entry.tokens) {

      const finalVars: string[] = []
      const definedVars: string[] = []

      for (const variable of token.variables) {
        const finalVarName = toCssVar("final", token.infix, variable.cssName)

        const chain = variable.allowed.map(prefix => {
          const value = variable.values[prefix];

          if (!value) {
            return `${prefix}`;
          }

          definedVars.push(`//${toCssVar(prefix, token.infix, variable.cssName)}: ${value};\n`)

          return `${prefix}:${value}`;
        })

        finalVars.push(`//${finalVarName}: 🔮 ${variable.key}: ${chain.join(" → ")};\n`)
      }

      const name =
        entry.name == token.infix
          ? entry.name
          : `${entry.name}-${token.infix}`

      const tokenVars = `\n//${name} {\n${finalVars.join("")}${definedVars.join("")}\n//}`

      output.push(tokenVars)
    }
  }
  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

${output}
`;

  return { filePath, content }
}