import path from 'node:path';
import type { FormatResult } from '../generateOutput.ts';
import { toCssVar } from '../../../../shared/tokenUtils/stringFormaters.ts';
import type { LspData } from '../../extract/assemblers/assembleLspData.ts';


export function formatLspFile(lspData: LspData): FormatResult {
  const output: string[] = []

  const filePath = path.resolve("./src/shared/generated/metadata/cssVariables.generated.ts")

  for (const token of lspData.tokens) {

    const finalVars: string[] = []
    const definedVars: string[] = []

    for (const variable of token.variables) {
      const finalVarName = toCssVar("final", token.infix, variable.cssName)

      const chain = variable.allowed.map(prefix => {
        const value = variable.values[prefix];

        if (!value) {
          return `${prefix}`;
        }

        definedVars.push(`//${toCssVar(prefix, token.infix, variable.cssName)}: ${value};\n`)

        return `${prefix}:${value}`;
      })

      finalVars.push(`//${finalVarName}: 🔮 ${variable.key}: ${chain.join(" → ")};\n`)
    }

    const name = token.infix
    // const name =
    //   group.name == token.infix
    //     ? group.name
    //     : `${group.name}-${token.infix}`

    const tokenVars = `\n//${name} {\n${finalVars.join("")}${definedVars.join("")}\n//}`

    output.push(tokenVars)
  }

  output.push(`\n//:root {\n${lspData.rgbVariables.map(variable => `//${variable};`).join("\n")}\n//}`)


  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

${output}
`;

  return { filePath, content }
}