import fs from "fs";
import path from "path";
import {
  toCamelCase,
  toPascalCase
} from "../../shared/compilerUtils/stringFormaters.ts";


function getImportPath(file, outputDir) {
  let relative = path
    .relative(outputDir, file)
    .replaceAll("\\", "/");

  const tokensIndex = relative.indexOf("tokens/");

  if (tokensIndex === -1) {
    throw new Error(`❌ Couldn't determine token import path: ${relative}`);
  }

  const afterTokens = relative.slice(
    tokensIndex + "tokens/".length
  );

  const parts = afterTokens.split("/");

  if (parts.length === 1) {
    // tokens/button.json
    relative = relative.replace(
      /\.jsonc?$/,
      ".json"
    );
  } else {
    // tokens/slider/thumb.json
    relative = relative.replace(
      /tokens\/[^/]+\/.*/,
      `tokens/${parts[0]}`
    );
  }

  return relative;
}


function dedupeEntries(entries, outputDir) {
  const seen = new Set();

  return entries.filter(({ file }) => {
    if (!file) {
      throw new Error("❌ Missing file");
    }

    const importPath = getImportPath(
      file,
      outputDir
    );

    if (seen.has(importPath)) {
      return false;
    }

    seen.add(importPath);

    return true;
  });
}


export default function buildComponentFile(components) {

  const outputDir = path.resolve(
    "./src/shared/generated/components"
  );

  const outputFile = path.join(
    outputDir,
    "components.ts"
  );


  const entries = [...components]
    .sort((a, b) =>
      a.name.localeCompare(b.name)
    )
    .map(({ name, file }) => {
      const camelName = toCamelCase(name);

      return {
        name,
        file,
        camelName,
        pascalName: toPascalCase(name),
        importName: `${camelName}Json`,
      };
    });


  // One entry per component
  const componentEntries = dedupeEntries(
    entries,
    outputDir
  );


  const imports = componentEntries
    .map(({ file, importName }) => {
      const importPath = getImportPath(
        file,
        outputDir
      );

      return `import ${importName} from "${importPath}";`;
    })
    .join("\n");


  const exports = componentEntries
    .map(({ camelName, pascalName, importName }) =>
      `
export const ${camelName}Style = convertJson(${importName});

export type ${pascalName}Style =
  StyleFromVars<
    typeof ${camelName}Style.vars,
    typeof ${camelName}Style.alwaysAllowed
  >;
`
    )
    .join("\n");


  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

import type {
  StyleFromVars
} from "@shared/compilerUtils/compiler.types";

import {
  convertJson
} from "@schema/convert";

${imports}

${exports}
`;


  fs.mkdirSync(outputDir, {
    recursive: true,
  });


  fs.writeFileSync(
    outputFile,
    content
  );
}