import fs from "fs";
import path from "path";
import { toCamelCase } from '../../../shared/compilerUtils/stringFormaters.ts';
import { toPascalCase } from '../../../shared/compilerUtils/stringFormaters.ts';

export default function buildPresetFile({ name, file, selectors }) {
  const pascalName = toPascalCase(name)
  const camelName = toCamelCase(name)

  const component = `${camelName}Preset`;
  const typeName = `${pascalName}Preset`;

  const generatedDir = path.resolve("./src/shared/generated/presets");
  const presetFile = path.join(generatedDir, `${camelName}.preset.ts`);

  const sortedSelectors = [...selectors].sort();

  let cssImport = path.relative(
    generatedDir,
    file
  );

  // make it valid for imports
  cssImport = cssImport.replaceAll("\\", "/");

  if (!cssImport.startsWith(".")) {
    cssImport = `${cssImport}`;
  }

  const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

import css from "./${cssImport}";

export const ${component} = {
${sortedSelectors
      .map(selector => `  ${selector}: css.${selector},`)
      .join("\n")}
} as const;

export type ${typeName} = keyof typeof ${component};
`;

  fs.writeFileSync(presetFile, content);
}