import { describe, expect, it } from 'vitest'

import { formatExtensionFile } from '../../../src/emitters/compose/format/formatExtensionFile.ts'
import type { ExtensionData } from '../../../src/types/emitter.types.ts'

function createExtensionData(
  overrides: Partial<ExtensionData> = {},
): ExtensionData {
  return {
    variables: [
      '--button-color',
      '--button-radius',
    ],
    ...overrides,
  }
}

describe('[EMITTER]', () => {
  describe('formatExtensionFile', () => {
    it('returns the extension output path', () => {
      const result = formatExtensionFile(
        createExtensionData(),
      )

      expect(result.outputFile)
        .toBe('metadata/extension.jsonc')
    })

    it('returns the extension result kind', () => {
      const result = formatExtensionFile(
        createExtensionData(),
      )

      expect(result.kind)
        .toBe('extension')
    })

    it('emits the generated file header', () => {
      const result = formatExtensionFile(
        createExtensionData(),
      )

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by cascade compiler.',
      )
    })

    it('emits variables as a JSONC array', () => {
      const result = formatExtensionFile(
        createExtensionData(),
      )

      expect(result.content).toContain(
        '"--button-color"',
      )

      expect(result.content).toContain(
        '"--button-radius"',
      )
    })

    it('separates multiple variables with commas', () => {
      const result = formatExtensionFile(
        createExtensionData({
          variables: [
            '--button-color',
            '--button-radius',
            '--button-size',
          ],
        }),
      )

      expect(result.content).toContain(
        '"--button-color",\n',
      )

      expect(result.content).toContain(
        '"--button-radius",\n',
      )

      expect(result.content).toContain(
        '"--button-size"',
      )
    })

    it('emits an empty array when there are no variables', () => {
      const result = formatExtensionFile(
        createExtensionData({
          variables: [],
        }),
      )

      expect(result.content).toContain('[')
      expect(result.content).toContain(']')

      expect(result.content).not.toContain('"--')
    })
  })
})