import { describe, expect, it } from 'vitest'

import { formatTokenFiles } from '../../../src/emitters/compose/format/formatTokenFiles.ts'
import type { TokenGroupData } from '../../../src/types/emitter.types.ts'

function createTokenGroup(
  overrides: Partial<TokenGroupData> = {},
): TokenGroupData {
  return {
    groupPath: '/tokens/button',
    name: 'button',
    styleName: 'buttonStyle',
    typeName: 'ButtonStyle',
    tokens: [
      {
        infix: 'button',
        variables: [
          {
            key: 'bg',
            cssName: 'back-ground',
            allowed: ['f'],
            values: {},
          },
          {
            key: 'color',
            cssName: 'color',
            allowed: ['p', 'f'],
            values: {},
          },
        ],
      },
    ],
    ...overrides,
  }
}

describe('[EMITTER]', () => {
  describe('formatTokenFiles', () => {
    it('returns no files when there is no token data', () => {
      expect(formatTokenFiles([])).toEqual([])
    })

    it('creates TypeScript, declaration, and JavaScript files', () => {
      const results = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(results.map(result => result.outputFile)).toEqual([
        'tokenModules/button.token.ts',
        'tokenModules/button.token.d.ts',
        'tokenModules/button.token.js',
      ])
    })

    it('returns tokens as the result kind', () => {
      const results = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(results.every(result => result.kind === 'tokens'))
        .toBe(true)
    })

    it('emits the generated file header', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by cascade.',
      )
    })

    it('emits the Cascade type imports', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'import type { StyleFromComponent, TokenComponent } from "cascade"',
      )
    })

    it('emits the component name and generated style name', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'export const buttonStyle = {',
      )

      expect(result.content).toContain(
        'component: "button",',
      )
    })

    it('emits token variables using their keys and names', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'bg: { name: "back-ground", allowed: ["f"]}',
      )

      expect(result.content).toContain(
        'color: { name: "color", allowed: ["p","f"]}',
      )
    })

    it('emits the token infix as the token property', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'button: {',
      )
    })

    it('emits multiple tokens', () => {
      const [result] = formatTokenFiles([
        createTokenGroup({
          tokens: [
            {
              infix: 'button',
              variables: [
                {
                  key: 'bg',
                  cssName: 'back-ground',
                  allowed: ['f'],
                  values: {},
                },
              ],
            },
            {
              infix: 'hover',
              variables: [
                {
                  key: 'bg',
                  cssName: 'back-ground',
                  allowed: ['s', 'f'],
                  values: {},
                },
              ],
            },
          ],
        }),
      ])

      expect(result.content).toContain('button: {')
      expect(result.content).toContain('hover: {')

      expect(result.content).toContain(
        'bg: { name: "back-ground", allowed: ["s","f"]}',
      )
    })

    it('emits the generated type', () => {
      const [result] = formatTokenFiles([
        createTokenGroup(),
      ])

      expect(result.content).toContain(
        'export type ButtonStyle = StyleFromComponent<typeof buttonStyle>;',
      )
    })

    it('emits empty token collections', () => {
      const [result] = formatTokenFiles([
        createTokenGroup({
          tokens: [],
        }),
      ])

      expect(result.content).toContain(
        'export const buttonStyle = {',
      )

      expect(result.content).toContain(
        'vars: {',
      )
    })

    it('creates three files for each token group', () => {
      const results = formatTokenFiles([
        createTokenGroup(),
        createTokenGroup({
          name: 'surface',
          styleName: 'surfaceStyle',
          typeName: 'SurfaceStyle',
        }),
      ])

      expect(results).toHaveLength(6)

      expect(results.map(result => result.outputFile)).toEqual([
        'tokenModules/button.token.ts',
        'tokenModules/button.token.d.ts',
        'tokenModules/button.token.js',
        'tokenModules/surface.token.ts',
        'tokenModules/surface.token.d.ts',
        'tokenModules/surface.token.js',
      ])
    })
  })
})