import { describe, expect, it } from 'vitest'

import { formatPresetFiles } from '../../../src/emitters/compose/format/formatPresetFiles.ts'
import type { PresetFileData } from '../../../src/types/emitter.types.ts'

function createPresetData(
  overrides: Partial<PresetFileData> = {},
): PresetFileData {
  return {
    name: 'button',
    typeName: 'ButtonPreset',
    selectors: [
      'primary',
      'secondary',
    ],
    ...overrides,
  }
}

describe('[EMITTER]', () => {
  describe('formatPresetFiles', () => {
    it('returns TypeScript and declaration files', () => {
      const result = formatPresetFiles([
        createPresetData(),
      ])

      expect(result.map(file => file.outputFile))
        .toEqual([
          'presets/button.preset.ts',
          'presets/button.preset.d.ts',
        ])
    })

    it('returns the presets result kind', () => {
      const result = formatPresetFiles([
        createPresetData(),
      ])

      expect(result.every(file => file.kind === 'presets'))
        .toBe(true)
    })

    it('emits the generated file header', () => {
      const [result] = formatPresetFiles([
        createPresetData(),
      ])

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by Cascade.',
      )
    })

    it('emits preset selectors in sorted order', () => {
      const [result] = formatPresetFiles([
        createPresetData({
          selectors: [
            'secondary',
            'primary',
            'active',
          ],
        }),
      ])

      expect(result.content).toContain(
        '  | "active"\n  | "primary"\n  | "secondary"',
      )
    })

    it('emits the preset union types', () => {
      const [result] = formatPresetFiles([
        createPresetData(),
      ])

      expect(result.content).toContain(
        'export type ButtonPreset =',
      )

      expect(result.content).toContain(
        'export type ButtonPresets =',
      )

      expect(result.content).toContain(
        '| ButtonPreset',
      )

      expect(result.content).toContain(
        '| ButtonPreset[]',
      )
    })

    it('formats multiple presets', () => {
      const result = formatPresetFiles([
        createPresetData(),
        createPresetData({
          name: 'surface',
          typeName: 'SurfacePreset',
          selectors: ['dark', 'light'],
        }),
      ])

      expect(result.map(file => file.outputFile))
        .toEqual([
          'presets/button.preset.ts',
          'presets/button.preset.d.ts',
          'presets/surface.preset.ts',
          'presets/surface.preset.d.ts',
        ])
    })
  })
})