import { describe, expect, it } from 'vitest'

import { formatLspFile } from '../../../src/emitters/compose/format/formatLspFile.ts'
import type {
  LspData,
  TokenData,
} from '../../../src/types/emitter.types.ts'

function createTokenData(
  overrides: Partial<TokenData> = {},
): TokenData {
  return {
    infix: 'button',
    variables: [
      {
        key: 'color',
        cssName: 'color',
        allowed: ['p', 'f'],
        values: {
          p: '#ff0000',
          f: '#000000',
        },
      },
    ],
    ...overrides,
  }
}

function createLspData(
  overrides: Partial<LspData> = {},
): LspData {
  return {
    rgbVariables: [],
    tokens: [],
    ...overrides,
  }
}

describe('[EMITTER]', () => {
  describe('formatLspFile', () => {
    it('returns the LSP output path', () => {
      const result = formatLspFile(
        createLspData(),
      )

      expect(result.outputFile)
        .toBe('metadata/lsp.ts')
    })

    it('returns the LSP result kind', () => {
      const result = formatLspFile(
        createLspData(),
      )

      expect(result.kind)
        .toBe('lsp')
    })

    it('emits the generated file header', () => {
      const result = formatLspFile(
        createLspData(),
      )

      expect(result.content).toContain(
        '// AUTO-GENERATED FILE.',
      )

      expect(result.content).toContain(
        '// DO NOT EDIT.',
      )

      expect(result.content).toContain(
        '// Generated by cascade compiler.',
      )
    })

    it('emits a token variable with its allowed value chain', () => {
      const result = formatLspFile(
        createLspData({
          tokens: [createTokenData()],
        }),
      )

      expect(result.content).toContain(
        '//button {',
      )

      expect(result.content).toContain(
        '//--final-button-color: 🔮 color: p:#ff0000 → f:#000000;',
      )
    })

    it('emits defined prefix variables with their values', () => {
      const result = formatLspFile(
        createLspData({
          tokens: [createTokenData()],
        }),
      )

      expect(result.content).toContain(
        '//--p-button-color: #ff0000;',
      )

      expect(result.content).toContain(
        '//--f-button-color: #000000;',
      )
    })

    it('emits prefixes without values in the chain', () => {
      const result = formatLspFile(
        createLspData({
          tokens: [
            createTokenData({
              variables: [
                {
                  key: 'color',
                  cssName: 'color',
                  allowed: ['p', 'f'],
                  values: {
                    p: '#ff0000',
                  },
                },
              ],
            }),
          ],
        }),
      )

      expect(result.content).toContain(
        '//--final-button-color: 🔮 color: p:#ff0000 → f;',
      )

      expect(result.content).not.toContain(
        '///--f-button-color:',
      )
    })

    it('uses the token infix as the block name', () => {
      const result = formatLspFile(
        createLspData({
          tokens: [
            createTokenData({
              infix: 'hover',
              variables: [],
            }),
          ],
        }),
      )

      expect(result.content).toContain(
        '//hover {',
      )
    })

    it('emits multiple token variables', () => {
      const result = formatLspFile(
        createLspData({
          tokens: [
            createTokenData({
              variables: [
                {
                  key: 'background',
                  cssName: 'background',
                  allowed: ['p'],
                  values: {
                    p: '#fff',
                  },
                },
                {
                  key: 'color',
                  cssName: 'color',
                  allowed: ['f'],
                  values: {
                    f: '#000',
                  },
                },
              ],
            }),
          ],
        }),
      )

      expect(result.content).toContain(
        '//--final-button-background: 🔮 background: p:#fff;',
      )

      expect(result.content).toContain(
        '//--final-button-color: 🔮 color: f:#000;',
      )
    })

    it('emits LSP RGB variables in the root block', () => {
      const result = formatLspFile(
        createLspData({
          rgbVariables: [
            '--button-color: rgb(100% 0% 0%)',
            '--button-background: rgb(0% 0% 0%)',
          ],
        }),
      )

      expect(result.content).toContain(
        '//:root {',
      )

      expect(result.content).toContain(
        '//--button-color: rgb(100% 0% 0%);',
      )

      expect(result.content).toContain(
        '//--button-background: rgb(0% 0% 0%);',
      )
    })

    it('emits empty token and root collections', () => {
      const result = formatLspFile(
        createLspData(),
      )

      expect(result.content).toContain(
        '//:root {',
      )
    })
  })
})