import type { TokenGroupFileData } from '../../data/extractors/extractTokenData.ts';
import type { FileOutput } from '../../format/buildOutput.ts';


export default function buildTokenFiles(tokenGroupData: TokenGroupFileData[]): FileOutput[] {
  const files: FileOutput[] = []

  for (const entry of tokenGroupData) {

    // const variables = entry.tokens.variables
    //   .toSorted((a, b) => a.name.localeCompare(b.name));

    const vars: string[] = [];

    for (const token of entry.tokens) {

      const varsRaw = token.variables.map((v) => {
        return `         ${v.key}: { name: "${v.name}", allowed: [${v.allowed.map((a) => `"${a}"`).join(",")}]}`
      }).join(",\n")



      const baseVar = `\n   ${token.infix}: {\n ${varsRaw} \n}`

      vars.push(baseVar)

    }


    const importStatement = `import type {
  StyleFromVars,
  TokenComponent
} from "@shared/tokenUtils/compiler.types"`

    const content = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by design-tokens-plugin.

${importStatement}

export const ${entry.styleName} = {
  component: "${entry.name}",

  vars: {   ${vars}
  }
} as const satisfies TokenComponent;

export type ${entry.typeName} = StyleFromVars<typeof ${entry.styleName}.vars>;
`;

    files.push({ filePath: entry.tokenFile, content })
  }

  return files
}