import type { PresetFileData } from '../../data/extractors/extractPresetData.ts';
import type { FileOutput } from '../../format/buildOutput.ts';


export default function buildPresetFiles(presetData: PresetFileData[]): FileOutput[] {
  const files: FileOutput[] = []

  for (const entry of presetData) {

    const sortedSelectors = entry.selectors.toSorted((a, b) => a.localeCompare(b));


    const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  
  import css from "${entry.cssImport}";
  
  export const ${entry.presetName} = {
  ${sortedSelectors
        .map(selector => `  ${selector}: css.${selector},`)
        .join("\n")}
  } as const;
  
  export type ${entry.typeName} = keyof typeof ${entry.presetName};
  `;

    files.push({ filePath: entry.presetFile, content })
  }

  return files
}