import type { FormatFileResult, TokenGroupData, VarData } from '../../../types/emitter.types.ts';


export function formatTokenFiles(tokenGroupData: TokenGroupData[]): FormatFileResult[] {
  const files: FormatFileResult[] = []

  const importStatement = (input: string) => `import type { ${input} } from "cascade"`

  for (const entry of tokenGroupData) {
    const outputBase = `tokenModules/${entry.name}.token`

    const plainVars: string[] = [];
    const declareVars: string[] = [];

    for (const token of entry.tokens) {

      const varsRaw = getVariables(token.variables, { readonly: false })

      const baseVar = `\n   ${token.infix}: {\n ${varsRaw} \n}`
      plainVars.push(baseVar)


      const varsDeclareRaw = getVariables(token.variables, { readonly: true })

      const baseDeclareVar = `\n   ${token.infix}: {\n ${varsDeclareRaw} \n}`
      declareVars.push(baseDeclareVar)
    }

    const tsContent = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by cascade.

${importStatement("StyleFromComponent, TokenComponent")}

export const ${entry.styleName} = {
  component: "${entry.name}",

  vars: {   ${plainVars}
  }
} as const satisfies TokenComponent;

export type ${entry.typeName} = StyleFromComponent<typeof ${entry.styleName}>;
`;

    const declareContent = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by cascade.

${importStatement("StyleFromComponent")}

export declare const ${entry.styleName}: {
  readonly component: "${entry.name}",

  readonly vars: {   ${declareVars}
  }
};

export type ${entry.typeName} = StyleFromComponent<typeof ${entry.styleName}>;
`;

    const jsContent = `// AUTO-GENERATED FILE.
// DO NOT EDIT.
// Generated by cascade.

export const ${entry.styleName} = {
  component: "${entry.name}",

  vars: {   ${plainVars}
  }
}
`;

    files.push(
      { outputFile: `${outputBase}.ts`, content: tsContent, kind: "tokens" },
      { outputFile: `${outputBase}.d.ts`, content: declareContent, kind: "tokens" },
      { outputFile: `${outputBase}.js`, content: jsContent, kind: "tokens" }
    )
  }

  return files
}


function getVariables(variables: VarData[], { readonly = false }): string {
  return variables.map((v) => {
    const allowed = `[${v.allowed.map((a) => `"${a}"`).join(",")}]`
    return readonly
      ? `readonly  ${v.key}: { readonly name: "${v.cssName}", readonly allowed: readonly ${allowed}}`
      : `${v.key}: { name: "${v.cssName}", allowed: ${allowed}}`
  }).join(",\n")
}