import type { FormatFileResult, PackageData } from '../../../types/emitter.types.ts';


export function formatPackageFile(data: PackageData): FormatFileResult[] {

  const jsExports = data.tokenNames
    .map(name => `export * from "./tokenModules/${name}.js"`)
    .join('\n')

  const tokenTypesExports = data.tokenNames
    .map(name => `export * from "./tokenModules/${name}"`)
    .join('\n')

  const presetTypesExports = data.presetNames
    .map(name => `export * from "./presets/${name}"`)
    .join('\n')

  const jsContent = `
  // oxlint-disable import/extensions
  // AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by Cascade-compiler.
  
  ${jsExports}
  `;

  const declarationContent = `
  // oxlint-disable import/extensions
  // AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by Cascade-compiler.
  
  ${tokenTypesExports}
  ${presetTypesExports}
  `;

  return [
    { outputFile: "index.js", content: jsContent, kind: "package" },
    { outputFile: "index.d.ts", content: declarationContent, kind: "package" }

  ]
}
