import type { ExtensionData, FormatFileResult } from '../../../types/emitter.types.ts';

export function formatExtensionFile(
  data: ExtensionData[],
): FormatFileResult {

  const sections = data.map(section => `{
  "cssPath": "${section.cssPath}",
  "variables": [
    ${section.variables.map(variable => `"${variable}"`).join(',\n')}
  ]
  }`).join(',\n')

  const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by cascade compiler.
  [
  ${sections}
  ]
  `

  const outputFile = "metadata/extension.jsonc"

  return { outputFile, content, kind: "extension" }
}