import type { FormatFileResult, PresetFileData } from '../../../types/emitter.types.ts';



export function formatPresetFiles(presetData: PresetFileData[]): FormatFileResult[] {
  const files: FormatFileResult[] = []

  for (const entry of presetData) {

    const outputBase = `presets/${entry.name}.preset`

    const sortedSelectors = entry.selectors.toSorted((a, b) => a.localeCompare(b));
    const presetValues = sortedSelectors.map(selector => `  | "${selector}"`).join('\n')

    const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by Cascade.
  
  export type ${entry.typeName} = 
  ${presetValues}
  
  export type ${entry.typeName}s = 
    | ${entry.typeName}
    | ${entry.typeName}[]
  `

    files.push(
      { outputFile: `${outputBase}.ts`, content: content, kind: "presets" },
      { outputFile: `${outputBase}.d.ts`, content: content, kind: "presets" }
    )
  }

  return files
}