import type { FormatResult } from '../generateOutput.ts';
import type { ExtensionData } from '../../extract/assemblers/assembleExtensionData.ts';

export function formatExtensionFile(
  data: ExtensionData,
): FormatResult {

  const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  [
    ${data.variables.map(variable => `"${variable}"`).join(",\n")}
  ]
  `;

  return { outputFile: data.outputFile, content };
}