import type { PresetFileData } from '../../extract/assemblers/assemblePresetData.js';
import type { FormatResult } from '../generateOutput.js';


export function formatPresetFiles(presetData: PresetFileData[]): FormatResult[] {
  const files: FormatResult[] = []

  for (const entry of presetData) {

    const sortedSelectors = entry.selectors.toSorted((a, b) => a.localeCompare(b));


    const content = `// AUTO-GENERATED FILE.
  // DO NOT EDIT.
  // Generated by design-tokens-plugin.
  
  import css from "${entry.cssImport}";
  
  export const ${entry.presetName} = {
  ${sortedSelectors
        .map(selector => `  ${selector}: css.${selector},`)
        .join("\n")}
  } as const;
  
  export type ${entry.typeName} = keyof typeof ${entry.presetName};
  `;

    files.push({ outputFile: entry.outputFile, content })
  }

  return files
}