# ==================== SETTINGS ====================

set shell := ["bash", "-c"]

workspace := "../ad-web-launcher.code-workspace"

# ================== DEFAULT ====================

default: help

# ================== DEVELOPMENT ====================

audit:
    npm audit

audit-all:
    ./scripts/run-cmd.sh audit

outdated:
    npm outdated

outdated-all:
    ./scripts/run-cmd.sh outdated || true

doctor:
    npm doctor

doctor-all:
    ./scripts/run-cmd.sh doctor

install:
    npm install

install-all:
    ./scripts/run-cmd.sh install
    ./scripts/run-cmd.sh install-scripts ls

update-all:
    ./scripts/run-cmd.sh update
    ./scripts/run-cmd.sh install-scripts ls

install-force package:
    ./scripts/install-force.sh {{ package }}

dev:
    npm run dev

preview:
    npm run preview

build:
    npm run build && ./scripts/deploy-android.sh

# ==================== QUALITY ====================

type:
    npm run type

type-all: 
    ./scripts/run-script.sh type

test *args:
    if [ -z "{{ args }}" ]; then \
        npm run test; \
    else \
        ./scripts/test-project.sh "{{ args }}"; \
    fi

test-all *args:
    ./scripts/run-script.sh test -- --run --reporter=dot {{args}}

coverage *args:
    if [ -z "{{ args }}" ]; then \
        npm run coverage; \
    else \
        npm run coverage -- "{{ args }}"; \
    fi

coverage-open:
    xdg-open coverage/index.html

lint *args:
    if [ -z "{{ args }}" ]; then \
        npm run lint; \
    else \
        ./scripts/lint.sh {{ args }}; \
    fi

stylelint *args:
    if [ -z "{{ args }}" ]; then \
        npm run stylelint; \
    else \
        npx stylelint {{ args }}; \
    fi

eslint *args:
    npx eslint {{ args }}

oxlint *args:
    npx oxlint {{ args }}

style: stylelint

ox: oxlint

es: eslint

knip *args:
    npm run knip -- {{ args }}

knip-all *args:
    ./scripts/knip-all.sh {{ args }}

# chmod +x scripts/index.sh <- an example for enabling a script

# ============== STYLE TOKENS LOG ==================

# CURRENTLY DEAD.... but needs to be implemented NO EMIT MODE
# tokens *args:
#     if [ -z "{{ args }}" ]; then \
#         npx tsx src/styleTokens/compiler/dryLogCompiler.ts; \
#     else \
#         npx tsx src/styleTokens/compiler/dryLogCompiler.ts {{ args }}; \
#     fi

# ==================== EXTENSIONS ====================

install-cvc:
    cd tools/extensions/css-variable-completion && npm run package
    code --install-extension tools/extensions/css-variable-completion/css-variable-completion-0.0.1.vsix --force

install-tcv:
    cd tools/extensions/token-compiler-vscode && npm run package
    code --install-extension tools/extensions/token-compiler-vscode/token-compiler-vscode-0.0.1.vsix --force

build-tc:
    cd tools/token-compiler && npm run build

install-tokens: build-tc install-tcv

compiler:
    cd tools/token-compiler && npm run cli -- exe ../..

# ==================== WORKSPACE ====================

open:
    @echo "🤖 Opening workspace from WSL..."
    code {{ workspace }}

open-new:
    @echo "🤖 Opening workspace in a new window..."
    code -n {{ workspace }}

# ==================== DELETABLES ====================

# Check whether the current TypeScript version is supported by typescript-eslint
check-ts-v:
    npm view typescript-eslint@latest peerDependencies
    npm view @typescript-eslint/parser@latest peerDependencies

check-deps *args:
    scripts/dependencies.sh {{ args }}

    
# ==================== HELP ====================

help:
    @echo ""
    @echo "==================== COMMAND SURFACE ===================="
    @echo ""
    @echo "[JUST] orchestration layer"
    @echo "→ just"
    @just --list
    @echo ""
    @echo "[NPM] package scripts"
    @echo "→ npm run"
    @npm pkg get scripts
